### ISSUE TITLE
Exception when playing sound in CLI

### ISSUE THREAD

**Issue by krzema12** [krzema12/fsynth#31]
```
:~/repos/fsynth$ java -jar cli/build/libs/cli.jar "Simple demo song"
Synthesized in 0.156 s
Playing...
Exception in thread "main" java.lang.IllegalArgumentException: Invalid format
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.createStream(PulseAudioDataLine.java:142)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:99)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:283)
	at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:402)
	at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:453)
	at it.krzeminski.fsynth.JvmSoundPlaybackKt.playAndBlockUntilFinishes(JvmSoundPlayback.kt:47)
	at it.krzeminski.fsynth.JvmSoundPlaybackKt.playOnJvm(JvmSoundPlayback.kt:19)
	at it.krzeminski.fsynth.ConsoleEntryPointKt.main(ConsoleEntryPoint.kt:11)
:~/repos/fsynth$ 
```

**Comment by krzema12** [comment]
It's caused by OpenJDK's runtime. When I use the CLI from within IntelliJ where Oracle's runtime is used, it works fine.

**Comment by krzema12** [comment]
https://searchcode.com/codesearch/view/17967005/ - the question is what sits in `supportedFormats`, and why OpenJDK doesn't support the format I use.

I'm just going to document this behavior in README, diving deeper and fixing it may not pay off.

**Comment by krzema12** [comment]
To make it work locally, I had to switch my `java` alias to point to Oracle JDK.
